services:
  execfi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Pass all env vars from .env file at build time
        - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
        - NEXT_PUBLIC_PROJECT_ID=${NEXT_PUBLIC_PROJECT_ID}
        - NEXT_PUBLIC_COIN_GECKO_API_KEY=${NEXT_PUBLIC_COIN_GECKO_API_KEY}
        - NEXT_PUBLIC_PRIVY_APP_ID=${NEXT_PUBLIC_PRIVY_APP_ID}
        - NEXT_PUBLIC_PRIVY_APP_SECRET=${NEXT_PUBLIC_PRIVY_APP_SECRET}
        - NEXT_PUBLIC_ZERO_DEV_PROJECT_ID=${NEXT_PUBLIC_ZERO_DEV_PROJECT_ID}
        - NEXT_PUBLIC_ZERO_DEV_PASSKEY_SERVER_URL=${NEXT_PUBLIC_ZERO_DEV_PASSKEY_SERVER_URL}
        - NEXT_PUBLIC_BUNDLER_RPC=${NEXT_PUBLIC_BUNDLER_RPC}
        - NEXT_PUBLIC_BICONOMY_BUNDLER=${NEXT_PUBLIC_BICONOMY_BUNDLER}
        - NEXT_PUBLIC_BICONOMY_PAYMASTER=${NEXT_PUBLIC_BICONOMY_PAYMASTER}
        - NEXT_PUBLIC_BICONOMY_PAYMASTER_API_KEY=${NEXT_PUBLIC_BICONOMY_PAYMASTER_API_KEY}
        - NEXT_PUBLIC_BICONOMY_API_KEY=${NEXT_PUBLIC_BICONOMY_API_KEY}
        - NEXT_PUBLIC_BICONOMY_PROJECT_ID=${NEXT_PUBLIC_BICONOMY_PROJECT_ID}
        - NEXT_PUBLIC_LIFI_KEY=${NEXT_PUBLIC_LIFI_KEY}
        - NEXT_PUBLIC_ALCHEMY_KEY=${NEXT_PUBLIC_ALCHEMY_KEY}
        - NEXT_PUBLIC_DEFAULT_CHAIN_ID=${NEXT_PUBLIC_DEFAULT_CHAIN_ID}
        - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
        - NEXT_PUBLIC_ENABLE_LIFI_EXECUTION=${NEXT_PUBLIC_ENABLE_LIFI_EXECUTION}
        - MAX_TX_AMOUNT_ETH=${MAX_TX_AMOUNT_ETH}
        - DAILY_SPEND_LIMIT_ETH=${DAILY_SPEND_LIMIT_ETH}
        - NEXT_PUBLIC_PRIVY_SIGNER_ID=${NEXT_PUBLIC_PRIVY_SIGNER_ID}
        - NEXT_PUBLIC_PRIVY_NATIVE_TRANSFER_POLICY_ID=${NEXT_PUBLIC_PRIVY_NATIVE_TRANSFER_POLICY_ID}
        - GAS_HEADROOM_MULT=${GAS_HEADROOM_MULT}
        - MIN_BALANCE_AFTER_TX_ETH=${MIN_BALANCE_AFTER_TX_ETH}
        - CONFIRM_BEFORE_SEND=${CONFIRM_BEFORE_SEND}
        - ENABLE_LIFI_PROVIDER=${ENABLE_LIFI_PROVIDER}
        - ENABLE_RELAY_PROVIDER=${ENABLE_RELAY_PROVIDER}
        - ENABLE_LOCAL_PROVIDER=${ENABLE_LOCAL_PROVIDER}
        - ENABLE_COINGECKO_PROVIDER=${ENABLE_COINGECKO_PROVIDER}
        - NEXT_PUBLIC_LIFI_API_KEY=${NEXT_PUBLIC_LIFI_API_KEY}
        - LIFI_API_KEY=${LIFI_API_KEY}
        - COINGECKO_API_KEY=${COINGECKO_API_KEY}
        - LIFI_PROVIDER_PRIORITY=${LIFI_PROVIDER_PRIORITY}
        - RELAY_PROVIDER_PRIORITY=${RELAY_PROVIDER_PRIORITY}
        - LOCAL_PROVIDER_PRIORITY=${LOCAL_PROVIDER_PRIORITY}
        - COINGECKO_PROVIDER_PRIORITY=${COINGECKO_PROVIDER_PRIORITY}
        - TOKEN_SEARCH_TIMEOUT_MS=${TOKEN_SEARCH_TIMEOUT_MS}
        - PROVIDER_HEALTH_CHECK_INTERVAL_MS=${PROVIDER_HEALTH_CHECK_INTERVAL_MS}
        - TOKEN_CACHE_TTL_SECONDS=${TOKEN_CACHE_TTL_SECONDS}
        - INTEGRATOR_LIFI=${INTEGRATOR_LIFI}
        - NEXT_PUBLIC_LISK_MAINNET=${NEXT_PUBLIC_LISK_MAINNET}
        - NEXT_PUBLIC_LISK_TESTNET=${NEXT_PUBLIC_LISK_TESTNET}
    ports:
      - "3290:3290"
    restart: unless-stopped
    container_name: execfi-app
