# Multi-stage build for production Next.js deployment
FROM node:20-alpine AS base

# Stage 1: Install dependencies
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm ci --legacy-peer-deps

# Stage 2: Build the application
FROM base AS builder
WORKDIR /app

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# All environment variables from .env will be passed at build time
# They need to be available during build since this is a client-side app
ARG NEXT_PUBLIC_APP_NAME
ARG NEXT_PUBLIC_PROJECT_ID
ARG NEXT_PUBLIC_COIN_GECKO_API_KEY
ARG NEXT_PUBLIC_PRIVY_APP_ID
ARG NEXT_PUBLIC_PRIVY_APP_SECRET
ARG NEXT_PUBLIC_ZERO_DEV_PROJECT_ID
ARG NEXT_PUBLIC_ZERO_DEV_PASSKEY_SERVER_URL
ARG NEXT_PUBLIC_BUNDLER_RPC
ARG NEXT_PUBLIC_BICONOMY_BUNDLER
ARG NEXT_PUBLIC_BICONOMY_PAYMASTER
ARG NEXT_PUBLIC_BICONOMY_PAYMASTER_API_KEY
ARG NEXT_PUBLIC_BICONOMY_API_KEY
ARG NEXT_PUBLIC_BICONOMY_PROJECT_ID
ARG NEXT_PUBLIC_LIFI_KEY
ARG NEXT_PUBLIC_ALCHEMY_KEY
ARG NEXT_PUBLIC_DEFAULT_CHAIN_ID
ARG OPENROUTER_API_KEY
ARG NEXT_PUBLIC_ENABLE_LIFI_EXECUTION
ARG MAX_TX_AMOUNT_ETH
ARG DAILY_SPEND_LIMIT_ETH
ARG NEXT_PUBLIC_PRIVY_SIGNER_ID
ARG NEXT_PUBLIC_PRIVY_NATIVE_TRANSFER_POLICY_ID
ARG GAS_HEADROOM_MULT
ARG MIN_BALANCE_AFTER_TX_ETH
ARG CONFIRM_BEFORE_SEND
ARG ENABLE_LIFI_PROVIDER
ARG ENABLE_RELAY_PROVIDER
ARG ENABLE_LOCAL_PROVIDER
ARG ENABLE_COINGECKO_PROVIDER
ARG NEXT_PUBLIC_LIFI_API_KEY
ARG LIFI_API_KEY
ARG COINGECKO_API_KEY
ARG LIFI_PROVIDER_PRIORITY
ARG RELAY_PROVIDER_PRIORITY
ARG LOCAL_PROVIDER_PRIORITY
ARG COINGECKO_PROVIDER_PRIORITY
ARG TOKEN_SEARCH_TIMEOUT_MS
ARG PROVIDER_HEALTH_CHECK_INTERVAL_MS
ARG TOKEN_CACHE_TTL_SECONDS
ARG INTEGRATOR_LIFI
ARG NEXT_PUBLIC_LISK_MAINNET
ARG NEXT_PUBLIC_LISK_TESTNET

ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME \
    NEXT_PUBLIC_PROJECT_ID=$NEXT_PUBLIC_PROJECT_ID \
    NEXT_PUBLIC_COIN_GECKO_API_KEY=$NEXT_PUBLIC_COIN_GECKO_API_KEY \
    NEXT_PUBLIC_PRIVY_APP_ID=$NEXT_PUBLIC_PRIVY_APP_ID \
    NEXT_PUBLIC_PRIVY_APP_SECRET=$NEXT_PUBLIC_PRIVY_APP_SECRET \
    NEXT_PUBLIC_ZERO_DEV_PROJECT_ID=$NEXT_PUBLIC_ZERO_DEV_PROJECT_ID \
    NEXT_PUBLIC_ZERO_DEV_PASSKEY_SERVER_URL=$NEXT_PUBLIC_ZERO_DEV_PASSKEY_SERVER_URL \
    NEXT_PUBLIC_BUNDLER_RPC=$NEXT_PUBLIC_BUNDLER_RPC \
    NEXT_PUBLIC_BICONOMY_BUNDLER=$NEXT_PUBLIC_BICONOMY_BUNDLER \
    NEXT_PUBLIC_BICONOMY_PAYMASTER=$NEXT_PUBLIC_BICONOMY_PAYMASTER \
    NEXT_PUBLIC_BICONOMY_PAYMASTER_API_KEY=$NEXT_PUBLIC_BICONOMY_PAYMASTER_API_KEY \
    NEXT_PUBLIC_BICONOMY_API_KEY=$NEXT_PUBLIC_BICONOMY_API_KEY \
    NEXT_PUBLIC_BICONOMY_PROJECT_ID=$NEXT_PUBLIC_BICONOMY_PROJECT_ID \
    NEXT_PUBLIC_LIFI_KEY=$NEXT_PUBLIC_LIFI_KEY \
    NEXT_PUBLIC_ALCHEMY_KEY=$NEXT_PUBLIC_ALCHEMY_KEY \
    NEXT_PUBLIC_DEFAULT_CHAIN_ID=$NEXT_PUBLIC_DEFAULT_CHAIN_ID \
    OPENROUTER_API_KEY=$OPENROUTER_API_KEY \
    NEXT_PUBLIC_ENABLE_LIFI_EXECUTION=$NEXT_PUBLIC_ENABLE_LIFI_EXECUTION \
    MAX_TX_AMOUNT_ETH=$MAX_TX_AMOUNT_ETH \
    DAILY_SPEND_LIMIT_ETH=$DAILY_SPEND_LIMIT_ETH \
    NEXT_PUBLIC_PRIVY_SIGNER_ID=$NEXT_PUBLIC_PRIVY_SIGNER_ID \
    NEXT_PUBLIC_PRIVY_NATIVE_TRANSFER_POLICY_ID=$NEXT_PUBLIC_PRIVY_NATIVE_TRANSFER_POLICY_ID \
    GAS_HEADROOM_MULT=$GAS_HEADROOM_MULT \
    MIN_BALANCE_AFTER_TX_ETH=$MIN_BALANCE_AFTER_TX_ETH \
    CONFIRM_BEFORE_SEND=$CONFIRM_BEFORE_SEND \
    ENABLE_LIFI_PROVIDER=$ENABLE_LIFI_PROVIDER \
    ENABLE_RELAY_PROVIDER=$ENABLE_RELAY_PROVIDER \
    ENABLE_LOCAL_PROVIDER=$ENABLE_LOCAL_PROVIDER \
    ENABLE_COINGECKO_PROVIDER=$ENABLE_COINGECKO_PROVIDER \
    NEXT_PUBLIC_LIFI_API_KEY=$NEXT_PUBLIC_LIFI_API_KEY \
    LIFI_API_KEY=$LIFI_API_KEY \
    COINGECKO_API_KEY=$COINGECKO_API_KEY \
    LIFI_PROVIDER_PRIORITY=$LIFI_PROVIDER_PRIORITY \
    RELAY_PROVIDER_PRIORITY=$RELAY_PROVIDER_PRIORITY \
    LOCAL_PROVIDER_PRIORITY=$LOCAL_PROVIDER_PRIORITY \
    COINGECKO_PROVIDER_PRIORITY=$COINGECKO_PROVIDER_PRIORITY \
    TOKEN_SEARCH_TIMEOUT_MS=$TOKEN_SEARCH_TIMEOUT_MS \
    PROVIDER_HEALTH_CHECK_INTERVAL_MS=$PROVIDER_HEALTH_CHECK_INTERVAL_MS \
    TOKEN_CACHE_TTL_SECONDS=$TOKEN_CACHE_TTL_SECONDS \
    INTEGRATOR_LIFI=$INTEGRATOR_LIFI \
    NEXT_PUBLIC_LISK_MAINNET=$NEXT_PUBLIC_LISK_MAINNET \
    NEXT_PUBLIC_LISK_TESTNET=$NEXT_PUBLIC_LISK_TESTNET

# Disable telemetry during build
ENV NEXT_TELEMETRY_DISABLED=1

# Build the application
RUN npm run build

# Stage 3: Production runner
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy static files
COPY --from=builder /app/public ./public

# Set correct permissions for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Copy standalone build
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3290

ENV PORT=3290
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
