[profile.default]
src = 'src'
out = 'out'
libs = ['lib', '../../lib']
test = 'test'
solc_version = '0.8.24'
optimizer = true
optimizer_runs = 200
evm_version = 'paris'
allow_paths = ['../../lib']

remappings = [
  '@openzeppelin/contracts/=../../lib/openzeppelin-contracts/contracts/',
  '@openzeppelin/contracts-upgradeable/=../../lib/openzeppelin-contracts-upgradeable/contracts/',
  'forge-std/=../../lib/forge-std/src/',
]

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true
