name: Build and Deploy to VPS

on:
  push:
    branches:
      - staging
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          build-args: |
            NEXT_PUBLIC_APP_NAME=${{ secrets.NEXT_PUBLIC_APP_NAME }}
            NEXT_PUBLIC_PROJECT_ID=${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
            NEXT_PUBLIC_COIN_GECKO_API_KEY=${{ secrets.NEXT_PUBLIC_COIN_GECKO_API_KEY }}
            NEXT_PUBLIC_PRIVY_APP_ID=${{ secrets.NEXT_PUBLIC_PRIVY_APP_ID }}
            NEXT_PUBLIC_PRIVY_APP_SECRET=${{ secrets.NEXT_PUBLIC_PRIVY_APP_SECRET }}
            NEXT_PUBLIC_ZERO_DEV_PROJECT_ID=${{ secrets.NEXT_PUBLIC_ZERO_DEV_PROJECT_ID }}
            NEXT_PUBLIC_ZERO_DEV_PASSKEY_SERVER_URL=${{ secrets.NEXT_PUBLIC_ZERO_DEV_PASSKEY_SERVER_URL }}
            NEXT_PUBLIC_BUNDLER_RPC=${{ secrets.NEXT_PUBLIC_BUNDLER_RPC }}
            NEXT_PUBLIC_BICONOMY_BUNDLER=${{ secrets.NEXT_PUBLIC_BICONOMY_BUNDLER }}
            NEXT_PUBLIC_BICONOMY_PAYMASTER=${{ secrets.NEXT_PUBLIC_BICONOMY_PAYMASTER }}
            NEXT_PUBLIC_BICONOMY_PAYMASTER_API_KEY=${{ secrets.NEXT_PUBLIC_BICONOMY_PAYMASTER_API_KEY }}
            NEXT_PUBLIC_BICONOMY_API_KEY=${{ secrets.NEXT_PUBLIC_BICONOMY_API_KEY }}
            NEXT_PUBLIC_BICONOMY_PROJECT_ID=${{ secrets.NEXT_PUBLIC_BICONOMY_PROJECT_ID }}
            NEXT_PUBLIC_LIFI_KEY=${{ secrets.NEXT_PUBLIC_LIFI_KEY }}
            NEXT_PUBLIC_ALCHEMY_KEY=${{ secrets.NEXT_PUBLIC_ALCHEMY_KEY }}
            NEXT_PUBLIC_DEFAULT_CHAIN_ID=${{ secrets.NEXT_PUBLIC_DEFAULT_CHAIN_ID }}
            OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}
            NEXT_PUBLIC_ENABLE_LIFI_EXECUTION=${{ secrets.NEXT_PUBLIC_ENABLE_LIFI_EXECUTION }}
            MAX_TX_AMOUNT_ETH=${{ secrets.MAX_TX_AMOUNT_ETH }}
            DAILY_SPEND_LIMIT_ETH=${{ secrets.DAILY_SPEND_LIMIT_ETH }}
            NEXT_PUBLIC_PRIVY_SIGNER_ID=${{ secrets.NEXT_PUBLIC_PRIVY_SIGNER_ID }}
            NEXT_PUBLIC_PRIVY_NATIVE_TRANSFER_POLICY_ID=${{ secrets.NEXT_PUBLIC_PRIVY_NATIVE_TRANSFER_POLICY_ID }}
            GAS_HEADROOM_MULT=${{ secrets.GAS_HEADROOM_MULT }}
            MIN_BALANCE_AFTER_TX_ETH=${{ secrets.MIN_BALANCE_AFTER_TX_ETH }}
            CONFIRM_BEFORE_SEND=${{ secrets.CONFIRM_BEFORE_SEND }}
            ENABLE_LIFI_PROVIDER=${{ secrets.ENABLE_LIFI_PROVIDER }}
            ENABLE_RELAY_PROVIDER=${{ secrets.ENABLE_RELAY_PROVIDER }}
            ENABLE_LOCAL_PROVIDER=${{ secrets.ENABLE_LOCAL_PROVIDER }}
            ENABLE_COINGECKO_PROVIDER=${{ secrets.ENABLE_COINGECKO_PROVIDER }}
            NEXT_PUBLIC_LIFI_API_KEY=${{ secrets.NEXT_PUBLIC_LIFI_API_KEY }}
            LIFI_API_KEY=${{ secrets.LIFI_API_KEY }}
            COINGECKO_API_KEY=${{ secrets.COINGECKO_API_KEY }}
            LIFI_PROVIDER_PRIORITY=${{ secrets.LIFI_PROVIDER_PRIORITY }}
            RELAY_PROVIDER_PRIORITY=${{ secrets.RELAY_PROVIDER_PRIORITY }}
            LOCAL_PROVIDER_PRIORITY=${{ secrets.LOCAL_PROVIDER_PRIORITY }}
            COINGECKO_PROVIDER_PRIORITY=${{ secrets.COINGECKO_PROVIDER_PRIORITY }}
            TOKEN_SEARCH_TIMEOUT_MS=${{ secrets.TOKEN_SEARCH_TIMEOUT_MS }}
            PROVIDER_HEALTH_CHECK_INTERVAL_MS=${{ secrets.PROVIDER_HEALTH_CHECK_INTERVAL_MS }}
            TOKEN_CACHE_TTL_SECONDS=${{ secrets.TOKEN_CACHE_TTL_SECONDS }}

      - name: Deployment complete
        run: |
          echo "✅ Image pushed to ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          echo "🔄 Watchtower will automatically deploy to VPS within 5 minutes"
